name: PR build and test

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Install detect-changes
      run: dotnet tool install -g --prerelease dotnet-detect-changes
    
    - name: Detect changes
      id: detect
      run: dotnet detect-changes ./test/ChangeDetector.Tests/ChangeDetector.Tests.csproj >> $GITHUB_OUTPUT
    
    - name: Debug
      run: echo ${{ steps.detect.outputs.changed }}
    
    - name: Run tests
      if: steps.detect.outputs.changed == 'true'
      run: echo "RUNNING TESTS"
